("a modifier" "")
("a series" "")
("abbreviation" "大略")
("about" "关于")
("about menu" "关于菜单")
("above" "以上")
("abstract" "大纲")
("accent" "")
("accept" "")
("accept all scripts" "")
("accept no scripts" "")
("accept script" "")
("acknowledgment" "感谢辞")
("acronym" "")
("action" "动作")
("activate" "")
("activate once" "")
("activate hidden" "")
("activation" "")
("acute" "")
("add package" "增加库")
("add switch after" "")
("add switch before" "")
("address" "住址")
("address block" "")
("advanced" "")
("advanced layout features" "")
("after" "之后")
("albanian" "")
("algorithm" "算法")
("align cell to the bottom" "")
("align cell to the left" "")
("align cell to the right" "")
("align cell to the top" "")
("align table at base of left column" "表格对齐左边")
("align table at base of middle column" "表格对齐中间")
("align table at base of origin column" "")
("align table at base of right column" "表格对齐右边")
("align table at fraction bar height" "")
("align table at the base of bottom row" "")
("align table at the base of middle row" "")
("align table at the base of origin row" "")
("align table at the base of top row" "")
("align table at the bottom" "")
("align table at the center" "")
("align table at the horizontal center" "")
("align table at the left" "")
("align table at the top" "")
("align table to the right" "")
("align text to the left" "")
("align text to the right" "")
("aligned" "")
("alignment" "对齐")
("all" "全部")
("allow" "")
("allowed extension" "")
("allowed reduction" "")
("alpha release" "")
("alt key" "alt 键")
("alternative specification" "")
("always" "总是")
("american" "美语")
("animation" "动画")
("and" "")
("angular" "")
("appendix" "附录")
("apply" "使用")
("apply macro" "")
("apply macro once" "")
("april" "")
("arab" "")
("arch series" "")
("archaic" "")
("architecture" "")
("argument" "")
("arithmetic" "算术")
("armenian" "")
("arrow" "")
("arrows" "")
("article" "论文")
("as on paper" "")
("assign" "")
("at fraction bar height" "")
("at the baseline" "")
("at the bottom" "")
("at the left" "")
("at the middle" "")
("at the right" "")
("at the top" "")
("attach" "")
("attach buffer to which project" "")
("august" "")
("author" "作者")
("authorize" "")
("automatic" "自动")
("automatically close brackets" "")
("automatically generated content" "")
("automatic quotes" "")
("autosave" "自动保存")
("axis" "")
("axiom" "公理")
("b series" "")
("back" "后退")
("background" "")
("background color" "背景色")
("background evaluations" "")
("backward replace" "")
("backward search" "")
("bad data format" "")
("bar" "")
("bard" "")
("base level" "")
("bashkirian" "")
("baseline" "基线")
("basic" "")
("basic communication using pipes" "")
("basic data types" "基本信息型态")
("basic types" "基本型态")
("be useful" "")
("become a TeXmacs developer" "成为TeXmacs的开发者")
("before" "")
("begin" "")
("below" "")
("beta release" "β版")
("bibliography" "参考文献")
("bibliography file" "参考文献文件")
("bibliography style" "参考文献的格式档")
("bibtex command" "bibtex 程序")
("big" "大")
("big figure" "大图片标题")
("big operator" "大的运算符号")
("big skip" "大间距")
("big table" "大表格标题")
("binary operation" "2项运算")
("binary relation" "2项运算")
("black" "黑色")
("blackboard bold" "粗黑体")
("blackboard math" "")
("blackletter" "")
("blank column" "空列")
("blank row" "空行")
("block content" "")
("blue" "蓝色")
("body" "")
("bold" "粗黑")
("book" "书籍")
("border" "边界")
("both" "两者")
("bottom" "底部")
("bottom border" "")
("bottom cell border" "")
("bottom cell padding" "")
("bottom margin" "")
("bottom padding" "")
("bottom table border" "")
("bottom table padding" "")
("branch" "分支")
("break" "断开")
("breaking" "")
("breve" "")
("british" "英语")
("broken white" "")
("brown" "褐色")
("browse" "浏览")
("browse web" "")
("browser" "浏览程序")
("buffer" "")
("bulgarian" "保加利亚文")
("bullet" "")
("bullets" "")
("by" "")
("by typing" "")
("bytes free" "0 bytes ")
("bytes used" "使用 bytes 总数")
("calligraphic" "")
("cancel" "取消")
("caps-lock key" "")
("case" "")
("cc" "")
("cell" "单元格")
("cell background color" "")
("cell border" "")
("cell height" "")
("cell operation mode" "")
("cell width" "")
("cells" "单元格")
("center" "居中")
("center text" "原文中间")
("centered" "居中对齐")
("centered block" "居中有框表格")
("centered tabular" "居中无框表格")
("change border of cell" "")
("change cell operation mode" "")
("change log" "")
("changes" "")
("chapter" "章")
("check" "")
("check text for spelling errors" "检查拼写")
("chinese" "中文")
("choice" "选择")
("citation" "引用")
("cite" "")
("class" "")
("clear" "清除")
("clear selection" "")
("clipped" "")
("clipped and magnified" "")
("clipped and resized" "")
("clone" "")
("clone window" "克隆窗口")
("close" "退出")
("close TeXmacs" "退出程序")
("close buffer" "退出暂存区")
("close document" "关闭文档")
("close session" "退出工作")
("close window" "关闭窗口")
("closing" "正在关闭中")
("closing style" "")
("code" "代码")
("color" "颜色")
("column" "列")
("column contains glued items" "")
("column to the left" "列(在左侧)")
("column to the right" "列(在右侧)")
("columns" "列")
("common formats" "")
("compact" "")
("compactification" "")
("compactify" "")
("compatibility with other formats" "")
("compile article" "文章编译")
("compile book" "书籍编译")
("compile buffer" "")
("compile project" "")
("completion" "完成")
("complex" "")
("compress" "压缩")
("concrete" "")
("condensed" "压缩")
("condition" "")
("configuration" "配置")
("contact" "")
("content" "属性")
("content tag" "属性标签")
("context dependent icons" "相关工具栏")
("continuation of" "延续")
("contribute" "参与")
("control the evaluation of expressions" "式子表现的控制")
("convention" "")
("converters" "转换器")
("converters to other data formats" "转换成其他格式")
("copy" "复制")
("copy text" "复制内文")
("copy to" "复制到")
("copying" "复制中")
("corollary" "推论")
("correct text" "")
("create web site" "生成站点")
("cursors" "游标")
("custom tab" "")
("customizing TeXmacs" "调整TeXmacs ")
("customizing the TeXmacs styles" "调整TeXmacs格式")
("custum tab" "")
("cut" "剪切")
("cut text" "剪切属性")
("cut to" "剪切到")
("cypriot" "")
("cyrillic" "")
("cyrillic input method" "")
("cyrillic italic right" "")
("czech" "捷克语")
("dancers" "")
("danish" "丹麦语")
("dark grey" "")
("dash" "")
("dashes" "")
("data conversion" "")
("data format" "")
("date" "日期")
("deactivate" "")
("deactivate table" "")
("debug" "调试")
("debugging tool" "调试工具")
("december" "")
("decimal comma" "小数逗号")
("decimal dot" "小数点")
("decorate atoms" "")
("default" "默认")
("default padding" "")
("definition" "定义")
("delete" "删除")
("delete column" "删除一行")
("delete row" "正在删除中")
("denominator" "分母")
("description" "描述")
("destination" "目标")
("detach" "")
("detailed" "详细")
("details in menus" "显示菜单")
("determinant" "行列式")
("devangari" "")
("developers guide" "程序源码")
("directory" "目录")
("disable" "禁用")
("disable first indentation" "")
("disable first indentation after" "")
("disable first indentation before" "")
("disable indentation" "")
("disable indentation after" "")
("disable indentation before" "")
("disactivate" "")
("disactivate once" "")
("disallow" "")
("distribute unused space" "分配未使用空隙")
("div" "")
("do not remap" "")
("document" "文档")
("document format" "文书格式")
("document style" "文书")
("document styles" "文书格式")
("documentation" "文档")
("documents are trees" "树状文书")
("dot" "")
("dots" "")
("double stroke" "")
("down" "")
("download" "下载")
("dpi" "")
("draw image" "绘制图形")
("draw over selection" "在选择区域内绘制")
("duplicate" "")
("dutch" "荷兰语")
("dynamic libraries" "")
("edit" "编辑")
("edit source tree" "编辑树状属性")
("editing tools" "编辑工具")
("email" "电子邮件")
("emphasize" "强调")
("emphasize text" "强调性属性")
("empty box" "空白的区域")
("enable change" "允许改变")
("enable first indentation" "")
("enable first indentation after" "")
("enable first indentation before" "")
("enable indentation" "")
("enable indentation after" "")
("enable indentation before" "")
("encl" "")
("end" "")
("english" "英语")
("enter a title" "输入标题")
("entire column" "整列")
("entire row" "整行")
("entire table" "整个表格")
("enumerate" "有序列表")
("enumerate|Alpha" "")
("enumerate|Roman" "")
("enumerate|alpha" "")
("enumerate|roman" "")
("env" "")
("environment" "环境")
("epilogue" "")
("equal" "等于")
("equation" "单行方程")
("equations" "多行方程")
("equivalent for" "")
("error" "错误")
("esperanto" "")
("etruscan" "")
("evaluate" "评价")
("evaluate scheme expression" "执行 scheme 表达式")
("even page footer" "偶数页页脚")
("even page header" "偶数页页眉")
("even page margin" "")
("even page left margin" "")
("even page shift" "")
("even page text" "")
("exact" "固定")
("exact horizontal" "")
("exact mode" "")
("exam" "试卷")
("example" "例子")
("exclusive" "排他的")
("exclusive or" "")
("executable" "可运行")
("execute" "运行")
("execute a TeXmacs command" "运行 TeXmacs 命令")
("execute system command" "运行系统命令")
("executive" "")
("exercise" "练习")
("expand" "扩展")
("explained" "")
("export" "导出")
("export as" "转换成")
("extend or normal" "")
("extern " "")
("extra" "")
("extract format" "")
("family" "")
("february" "")
("figure" "图")
("file" "文件")
("file name" "文件名")
("file not found" "无此文件")
("fill color" "填充色")
("find next match" "查找下一条信息")
("find text" "查找属性")
("finnish" "芬兰语")
("first" "最前面")
("first contact" "")
("first indentation" "首行缩进")
("first item" "")
("first page" "")
("first start" "开始第一次")
("flat" "扁平")
("flexibility" "弹性")
("flexibility factor for vertical spacing" "")
("floating figure" "浮动图形")
("floating object" "浮动对象")
("floating table" "浮动表格")
("fold" "折叠")
("fold input field" "")
("folded" "")
("font" "字体")
("font base size" "字体基本大小")
("font dpi" "")
("font family" "")
("font name" "")
("font series" "")
("font shape" "")
("font size" "")
("font type" "")
("font variant" "")
("fonts" "")
("footer" "页脚")
("footnote" "脚注")
("for" "")
("foreground" "前景色")
("foreign" "")
("format" "格式")
("formatted and structured output" "")
("formatted date" "")
("formatting" "格式中")
("formula" "公式")
("formula style" "")
("forward" "前进")
("forward replace" "")
("forward search" "")
("fraction" "分数")
("french" "法文")
("full manuals" "完全手册")
("full screen mode" "全屏模式")
("function" "")
("functional" "")
("further customization" "")
("future changes" "")
("gNU TeXmacs comes without any form of legal warranty" "GNU TeXmacs 无任何保证")
("gNU TeXmacs falls under the GNU general public license" "GNU TeXmacs 使用 GNU general public license 授权")
("general architecture of TeXmacs" "")
("general negation" "")
("general note" "")
("generating font file" "字体文件制作中")
("generic" "普通")
("geometry" "几何")
("georgian" "")
("german" "德文")
("getting started" "")
("glossary" "术语")
("glossary entry" "术语项")
("glue" "")
("glue decorations" "")
("go" "转到")
("gothic" "")
("graphical interface" "")
("graphics" "图形")
("grave" "")
("greater" "")
("greater or equal" "")
("greek" "")
("greek letter" "")
("green" "绿色")
("grey" "灰色")
("grids" "网格")
("group" "")
("h modifier" "")
("happy typing" "")
("has been aborted" "")
("has completed its task" "")
("hat" "")
("header" "页眉")
("header and footer" "页眉页脚")
("hebrew" "")
("height" "高度")
("height is exactly the specified height" "")
("height is maximum of specified height and box height" "")
("height is minimum of specified height and box height" "")
("height magnification" "")
("help" "帮助")
("help me" "")
("help us" "帮助我们")
("here" "这里")
("hidden" "")
("home" "")
("homepage" "主页")
("horizontal" "")
("horizontal cell alignment" "")
("horizontal ink separation" "")
("horizontal part" "水平部分")
("horizontal position" "")
("horizontal space" "")
("horizontal alignment" "水平对齐")
("horizontally align cell to the base" "")
("horizontally center the cell" "")
("how much longer may pages become" "")
("how much shorter may pages become" "")
("huge" "巨大")
("hungarian" "匈牙利语")
("hybrid command" "")
("hyperlink" "超链接")
("hyphenation" "连字符")
("icelandic" "")
("if" "")
("if hyphenated" "有连字符时")
("image" "图片")
("image links" "")
("implementation" "")
("import" "导入")
("improving the current implementation" "")
("inactive" "")
("include" "包含")
("include a document" "")
("include file" "")
("inclusion into TeXmacs" "")
("inclusions" "")
("indent" "")
("indentation flag" "对齐标签")
("index" "索引")
("index entry" "索引项")
("index level" "")
("informative flags" "")
("inline arguments" "")
("input mode" "")
("insert" "插入")
("insert Pr" "")
("insert a TeXmacs symbol" "")
("insert a big operator" "")
("insert a binary operation" "")
("insert a binary relation" "")
("insert a blackboard bold character" "")
("insert a bold calligraphic character" "")
("insert a bold character" "")
("insert a calligraphic character" "")
("insert a condition" "")
("insert a control flow instruction" "")
("insert a fraction" "")
("insert a fraktur character" "")
("insert a greek character" "")
("insert a large left delimiter" "")
("insert a large right delimiter" "")
("insert a large separator" "")
("insert a left subscript" "")
("insert a link" "")
("insert a miscellaneous symbol" "")
("insert a new branch" "")
("insert a new item" "")
("insert a numerical operation" "")
("insert a picture" "")
("insert a square root" "")
("insert a table" "")
("insert a table or a matrix" "")
("insert a textual operation" "")
("insert a wide symbol above" "")
("insert a wide symbol below" "")
("insert an" "")
("insert an accent" "")
("insert an arrow" "")
("insert an environment" "")
("insert an n" "")
("insert an operation on tuples" "")
("insert appendix" "")
("insert arccos" "")
("insert arcsin" "")
("insert arctan" "")
("insert arg" "")
("insert argument" "")
("insert author" "")
("insert automatically generated content" "")
("insert big contour integral" "")
("insert big coproduct" "")
("insert big direct sum" "")
("insert big dotted point" "")
("insert big integral" "")
("insert big intersection" "")
("insert big logical and" "")
("insert big logical or" "")
("insert big product" "")
("insert big square union" "")
("insert big summation" "")
("insert big tensor product" "")
("insert big union" "")
("insert big union sum" "")
("insert big vertical space" "")
("insert chapter" "")
("insert column" "")
("insert column to the left" "")
("insert column to the right" "")
("insert cos" "")
("insert cosh" "")
("insert cot" "")
("insert coth" "")
("insert csc" "")
("insert deg" "")
("insert det" "")
("insert dim" "")
("insert dollar" "")
("insert equation" "")
("insert executable markup" "")
("insert exp" "")
("insert fields" "")
("insert footnote" "")
("insert formula" "")
("insert gcd" "")
("insert hom" "")
("insert horizontal interword space" "")
("insert image" "插入图片")
("insert inactive markup" "")
("insert inf" "")
("insert input field above" "")
("insert input field below" "")
("insert ker" "")
("insert lg" "")
("insert lim" "")
("insert liminf" "")
("insert limsup" "")
("insert ln" "")
("insert log" "")
("insert macro" "")
("insert mathematics" "")
("insert max" "")
("insert medium horizontal space" "")
("insert medium vertical space" "")
("insert min" "")
("insert negative horizontal space" "")
("insert new item or number" "")
("insert new rows or columns" "")
("insert or delete rows or columns" "")
("insert row" "")
("insert row above" "")
("insert row below" "")
("insert sec" "")
("insert section" "输入节(section) ")
("insert sharp" "")
("insert sin" "")
("insert sinh" "")
("insert small horizontal space" "")
("insert small vertical space" "")
("insert structural markup" "")
("insert subsection" "")
("insert subsubsection" "")
("insert sup" "")
("insert tan" "")
("insert tanh" "")
("insert text field" "")
("insert thick horizontal space" "")
("insert title" "插入标题")
("insert value" "")
("interactive command" "")
("interactive questions" "显示询问")
("interfacing" "用户界面")
("interfacing TeXmacs with other systems" "")
("interjection" "")
("interline separation" "行间分隔")
("interline space" "行间空隔")
("internationalization" "")
("interparagraph space" "段落间空隔")
("interrupt execution" "")
("introduction" "")
("invisible" "")
("invisible citation" "")
("irish" "")
("is running" "")
("is tuple" "")
("ispell does not respond" "")
("ispell is already busy" "")
("italian" "意大利语")
("italic" "斜体")
("italic right" "")
("itemize" "无序列表")
("january" "")
("japanese" "日文")
("july" "")
("june" "")
("justified" "两端对齐")
("justify text" "")
("key" "")
("keyboard" "键盘")
("keyboard equivalent" "")
("keyboard modifiers" "")
("keyboard shorthand" "")
("keymaps" "")
("keyword" "关键字")
("keywords" "关键语")
("kill" "")
("known bugs" "")
("korean" "韩语")
("label" "标签")
("landscape" "")
("language" "语言")
("large" "大")
("large closing bracket" "")
("large delimiter" "")
("large opening bracket" "")
("large separator" "")
("last" "最后面")
("last page" "")
("latex command" "")
("latin" "")
("layout" "")
("left" "左边")
("left arrow" "")
("left border" "左端")
("left cell border" "")
("left cell padding" "")
("left margin" "左端空白")
("left padding" "")
("left prime" "")
("left ragged" "左对齐")
("left slanted" "左倾斜")
("left subscript" "")
("left superscript" "")
("left surrounding" "")
("left table border" "")
("left table padding" "")
("legal" "")
("lemma" "引理")
("length" "")
("less" "")
("less or equal" "")
("letter" "信件")
("license" "")
("light" "细黑")
("light grey" "")
("limitations" "")
("limits" "")
("line" "")
("line break" "")
("line properties" "线属性")
("line stretch" "")
("link" "链接")
("link image" "链接图片")
("linking tool" "链接工具")
("list" "")
("list of figures" "图形目录")
("list of tables" "表格目录")
("load" "打开")
("load LaTeX file" "")
("load TeX file" "")
("load TeXmacs file" "")
("load TeXmacs style file" "")
("load a file" "")
("load buffer" "")
("load file" "")
("load html file" "")
("load image" "")
("load in new window" "")
("load latex file" "")
("load more recent autosave file" "打开最近自动保存的文件")
("load tex file" "打开 TeX 文件")
("load verbatim file" "")
("loaded" "")
("long" "细长")
("look and feel" "快捷键风格")
("look up" "")
("lower border" "下端")
("m modifier" "")
("macro" "宏命令")
("magenta" "紫红")
("magic" "")
("magnification" "放大比例")
("magnified" "")
("main" "")
("main icon bar" "主要工具栏")
("major changes" "")
("make a page insertion" "")
("make a subscript" "")
("make a superscript" "")
("make acute" "")
("make bar" "")
("make check" "")
("make fraction" "")
("make grave" "")
("make hat" "")
("make label" "")
("make negation" "")
("make page reference" "")
("make reference" "")
("make square root" "")
("make tilde" "")
("make title" "表题制作")
("make vector" "")
("making donations" "")
("manual" "用户手册")
("map to" "")
("march" "")
("margins" "边白")
("margins as on paper" "")
("master" "")
("master file" "")
("math" "")
("math font" "")
("math font family" "")
("math font series" "")
("math font shape" "")
("mathematical" "")
("mathematical and customized input" "")
("mathematical font" "")
("mathematical formulas" "")
("mathematical input" "")
("mathematical typesetting" "")
("mathematics" "数学")
("matrix" "矩阵")
("maximal" "最大")
("maximal number of columns" "")
("maximal number of rows" "")
("maximum mode" "")
("may" "")
("medium" "适中")
("medium skip" "中间距")
("meminfo" "")
("merge" "")
("messy" "")
("meta key" "")
("middle" "")
("minimal" "最小")
("minimal number of columns" "")
("minimal number of rows" "")
("minimum mode" "")
("minus" "")
("miscellaneous" "杂项")
("miscellaneous features" "")
("mod" "")
("mode" "模式")
("modifier" "")
("modify cell alignment" "")
("modify cell border" "")
("modify cell padding" "")
("modify cell size" "")
("modify table border" "")
("modify table padding" "")
("mongolian" "")
("more information about GNU TeXmacs can be found in the Help" "更多关于 GNU TeXmacs 的信息可查看帮助")
("mosaic" "")
("move down" "")
("move object" "")
("move to the right when finished" "")
("move up" "")
("multiline input" "")
("mutator tags" "")
("my documents" "个人文档")
("n-th" "")
("n-th root" "")
("name" "名称")
("negation" "")
("never" "从不")
("new" "新建")
("new buffer" "")
("new column" "添加一行")
("new double page" "")
("new double page before" "")
("new item" "")
("new line" "添加一行")
("new number" "")
("new page" "添加一页")
("new page before" "")
("new paragraph" "")
("new roman" "")
("new row" "")
("new table" "")
("next" "后一个")
("next line" "")
("no changes need to be saved" "没有任何更改需要保存")
("no dictionary for" "")
("no first indentation" "")
("no indentation" "")
("no line break" "")
("no matches found" "")
("no matches found for" "")
("no more matches for" "")
("no more redo information available" "")
("no more undo information available" "")
("no name" "无标题文件")
("no page break after" "")
("no page break before" "")
("no spelling errors found in text" "")
("no style" "无风格")
("none" "无")
("normal" "标准")
("norwegian" "挪威文")
("not" "")
("not equal" "")
("not found" "")
("notation" "记法")
("note" "注记")
("november" "")
("number" "")
("number of columns" "列数")
("number equation" "")
("numbered equation" "")
("numbered equations" "")
("numerator" "分子")
("numeric" "")
("objectives" "")
("occurrences" "")
("october" "")
("odd page footer" "奇数页页脚")
("odd page header" "奇数页页眉")
("odd page margin" "")
("odd page left margin" "")
("odd page right margin" "")
("odd page shift" "")
("odd page text" "")
("off" "关闭")
("ok" "")
("old english" "")
("old slavonic" "")
("old style" "")
("on" "")
("on cells" "")
("on columns" "")
("on entire table" "")
("on rows" "")
("one spelling error has been corrected" "")
("online documentation" "")
("online help" "在线说明")
("only inline tags" "")
("open" "打开")
("open a new buffer" "")
("open new window" "新开窗口")
("opening" "")
("operation mode" "操作模式")
("operation on named selection" "")
("operation on primary selection" "")
("operation on secondary selection" "")
("operation on ternary selection" "")
("optical" "")
("option" "")
("options" "")
("or" "")
("orange" "橙色")
("orientation" "")
("origin" "")
("original welcome message" "")
("other" "其它")
("other pages" "其它页")
("other projects" "")
("other style" "其它风格")
("outlined roman" "")
("over" "")
("overbrace" "")
("overline" "上划线")
("padding" "补白")
("page" "页面")
("page bottom margin" "")
("page break" "")
("page break before" "")
("page height" "")
("page insertion" "页插入")
("page layout" "")
("page number text" "设定页码文字")
("page numbering" "页码")
("page reference" "页面参考")
("page right margin" "")
("page setup" "页面设置")
("page top margin" "页面上縁")
("page type" "页面种类")
("page width" "页面宽长")
("paper" "")
("paper type" "")
("papyrus" "")
("paragraph" "段落")
("paragraph mode" "")
("paragraph width" "")
("part" "部分")
("past changes" "")
("paste" "粘贴")
("paste from" "粘贴自")
("paste text" "")
("path" "")
("perform operations on cells" "")
("perform operations on columns" "")
("perform operations on entire table" "")
("perform operations on rows" "")
("permanent" "")
("person" "")
("personal dictionary has been modified" "")
("phantasy" "")
("philosophy" "")
("phoenician" "")
("phonetic" "")
("pink" "粉红")
("plain block" "普通有框表格")
("plain tabular" "普通无框表格")
("planned changes" "")
("plans for the future" "")
("please" "")
("please wait" "请稍后")
("plugin" "")
("plugins" "")
("plus" "")
("point style" "点形状")
("polish" "波兰语")
("porting TeXmacs to other platforms" "")
("portrait" "")
("portuguese" "葡萄牙语")
("position" "")
("position float" "")
("position floating object" "")
("position the table" "")
("postscript" "")
("postscript image" "")
("pre-alpha release" "")
("preamble" "")
("preamble mode" "")
("preferences" "首选项")
("presentation" "演讲")
("presentation mode" "演讲模式")
("presentation tag" "展示标签")
("preview before printing" "")
("preview command" "")
("preview with ghostview" "在 ghostview 中预览")
("previous" "前一个")
("primary" "")
("prime" "")
("print" "打印")
("print all" "全部打印")
("print all to file" "全部打印为文件")
("print page selection" "选择打印")
("print page selection to file" "选择打印为文件")
("print to postscript file" "印成 postscript 文件")
("printer" "打印机")
("printer dpi" "")
("printing command" "")
("problem" "问题")
("professional" "专业")
("prog" "")
("prog font" "")
("prog font family" "")
("prog font series" "")
("prog font shape" "")
("program" "")
("program font" "")
("program mode" "")
("programming" "")
("progressive" "")
("project" "项目")
("projects" "项目计划")
("prologue" "")
("prompt on scripts" "")
("prompts and default input" "")
("proof" "证明")
("proportional" "比例")
("proportional typewriter" "")
("proposition" "命题")
("query replace" "")
("quit" "")
;("quotation" "引用")
("quote" "")
("range" "")
("really close it" "")
("really huge" "非常大")
("really quit" "")
("really tiny" "非常小")
("recover autosave file" "复元自动保存文件")
("red" "红色")
("redo" "恢复")
("redo undone changes" "")
("reduce bottom margin by" "")
("reduce left margin by" "")
("reduce margins" "")
("reduce right margin by" "")
("reduce top margin by" "")
("reduction even page margin" "")
("reduction odd page margin" "")
("reduction page bottom margin" "")
("reduction page right margin" "")
("reduction page top margin" "")
("reference" "参考")
("reference guide" "参考指南")
("reference guide for the TeXmacs primitives" "")
("reference guide for the standard TeXmacs styles" "")
("references" "参考")
("regular" "")
("release" "")
("reload" "重新装入")
("remark" "注意")
("remote" "远程")
("remote connections" "远程连接")
("remove" "删除")
("remove all output fields" "")
("remove fields" "")
("remove input field" "")
("remove input field above" "")
("remove number" "")
("remove package" "取消库")
("remove this switch" "")
("renumber this page" "修改当前页码")
("repeat" "")
("repeat object" "")
("replace" "替换")
("replace by" "被替换")
("replaced" "")
("replaced one occurrence" "")
("reset" "")
("resize object" "")
("resized" "")
("results of the search for" "")
("return" "")
("revert" "恢复")
("revert buffer" "")
("right" "右边")
("right arrow" "")
("right border" "右端")
("right cell border" "")
("right cell padding" "")
("right margin" "右端空白")
("right padding" "")
("right ragged" "右对齐")
("right subscript" "")
("right superscript" "")
("right surrounding" "")
("right table border" "")
("right table padding" "")
("rigid" "")
("rigid horizontal" "")
("rigid space" "")
("romanian" "罗马尼亚语")
("root" "根")
("rotate backward" "")
("rotate forward" "")
("row" "行")
("row above" "行(在上方)")
("row below" "行(在下方)")
("row contains glued items" "")
("rows" "行")
("runic" "")
("running author" "")
("running title" "")
("russian" "俄语")
("sample" "")
("sans serif" "")
("save" "保存")
("save TeXmacs file" "存成 TeXmacs 档")
("save TeXmacs style file" "存成 TeXmacs 格式档")
("save as" "另存为")
("save as LaTeX" "另存为 LaTeX 文件")
("save as TeX" "另存为 TeX 文件")
("save buffer" "保存暂存盘")
("save buffer as" "另存暂存盘为")
("save file" "保存文件")
("save html file" "存为 html 文件")
("save image" "保存图形文件")
("save latex file" "保存 LaTeX 文件")
("save tex file" "保存TeX文件")
("save this buffer" "保存暂存区信息")
("save verbatim file" "存为  verbatim 文件")
("saved" "保存完成")
("scheme command" "")
("scheme extensions" "扩展语言")
("screen layout" "")
("screen margins" "")
("script" "脚本")
("scripts" "脚本")
("script above" "")
("script below" "")
("script script size" "")
("script size" "")
("scripts not accepted" "")
("search" "查找")
("search words in my documents" "")
("search words in the documentation" "")
("search words in the source code" "")
("searching" "")
("secondary" "")
("section" "节")
("security" "安全")
("see" "")
("select a document style" "")
("select a foreground color" "")
("select a language" "")
("selected region" "")
("selection" "")
("selections" "选择")
("seminar" "会议")
("sending commands to TeXmacs" "")
("separation between lines" "")
("separation between paragraphs" "")
("separator" "")
("september" "")
("serb" "")
("series" "字型")
("series|right" "")
("session" "进程")
("session name" "")
("session type" "")
("sessions" "进程")
("set" "")
("set background color of cell" "")
("set cell mode" "")
("set extension center" "")
("set height" "")
("set height of cell" "")
("set margins" "")
("set n" "")
("set or get environment variables" "")
("set paragraph margins" "")
("set paragraph mode" "")
("set printer dpi" "")
("set printing command" "")
("set span" "设置合并")
("set special cell properties" "")
("set special table properties" "")
("set text width" "")
("set width" "")
("set width of cell" "")
("settings" "")
("setup printer" "")
("shape" "字形")
("shift-down" "")
("shift-right" "")
("short" "")
("show" "")
("show header and footer" "")
("show hidden" "")
("show on screen" "")
("shrinking factor" "收缩比例")
("signature" "")
("size" "大小")
("size tag" "大小标签")
("size limits" "")
("slanted" "倾斜")
("sloppy" "")
("slovene" "斯洛文尼亚语")
("small" "小")
("small caps" "小体大写")
("small figure" "小图片标题")
("small skip" "小间距")
("small table" "小表格标题")
("source" "源码")
("source code" "程序源码")
("source tags" "")
("space" "空白")
("space between lines" "")
("space between paragraphs" "")
("spacing" "间隔")
("spanish" "西班牙语")
("special" "特定")
("special properties" "特殊属性")
("specific" "指定")
("spell" "拼写")
("spell checking complete" "拼写检查完成")
("spelling error" "拼写错误")
("spelling errors have been corrected" "拼写错误更正完成")
("split" "")
("split session" "")
("square root" "平方根")
("standard environment variables" "")
("standard formats" "")
("standard TeXmacs styles" "")
("start" "开始")
("start a new chapter" "")
("start a new section" "")
("start an interactive session" "")
("status bar" "状态栏")
("stretch" "")
("stretchable" "")
("stretchable horizontal" "")
("stretchable vertical" "")
("stretched" "")
("stroke" "")
("strokes" "")
("strong" "加粗")
("structural" "")
("style" "风格")
("styles" "")
("stylesheet language" "")
("sub" "")
("subparagraph" "小段落")
("subscript" "下标")
("subsection" "小节")
("subsub" "")
("subsubsection" "子节")
("subtable" "子表格")
("subtitle" "副标题")
("summary" "")
("summary of the principal TeXmacs tags" "")
("superpose" "")
("superposed" "")
("superscript" "上标")
("swedish" "瑞典语")
("swiss" "")
("switch" "")
("switch to first" "")
("switch to formula style" "")
("switch to last" "")
("switch to next" "")
("switch to previous" "")
("switching and folding" "")
("symbol" "")
("system command" "")
("system environment variables" "")
("tab" "")
("table" "表格")
("table command" "")
("table of contents" "目次")
("tables" "")
("tabular" "")
("tabular material" "")
("taiwanese" "台湾话")
("teXmacs as an interface" "")
("teXmacs fonts" "")
("teXmacs notice" "")
("teXmacs plugins" "")
("teXmacs style files" "")
("ternary" "")
("test" "捡测")
("tex" "")
("text" "文本")
("text box alignment" "文本框对齐")
("text font" "")
("text height correction" "文本高度修正")
("text width" "")
("texts" "")
("th century bc" "")
("th root" "")
("thai" "")
("the TeXmacs authors" "")
("the TeXmacs format" "")
("the application did not send its usual startup banner" "")
("the application does not reply" "")
("the application is already running" "")
("the boxes produced by the typesetter" "")
("the buffer has not been saved" "暂存区信息尚未保存")
("the graphical user interface" "")
("the leaves of TeXmacs trees" "")
("the mycas example" "")
("the primitive TeXmacs constructs" "")
("the standard TeXmacs styles" "")
("theorem" "定理")
("there are unsaved files" "尚有文件尚未保存保存")
("this buffer has not been saved" "现工作的暂存区信息尚未保存")
("this column" "此列")
("this document has been produced using" "此文档由制作")
("this line" "")
("this page" "")
("this page footer" "")
("this page header" "")
("this row" "此行")
("thumbnails" "缩略图")
("tilda" "")
("tilde" "")
("times" "")
("tiny" "细小")
("title" "标题")
("to the left" "")
("to the right" "")
("today" "今天")
("tools" "工具")
("top" "顶部")
("top border" "")
("top cell border" "")
("top cell padding" "")
("top level" "")
("top margin" "")
("top padding" "")
("top table border" "")
("top table padding" "")
("translate" "")
("tree" "")
("tuple" "")
("turkish" "土耳其文")
("tutorial" "入门教程")
("type" "")
("type a latex command followed by" "")
("type body" "")
("type denominator" "")
("type numerator" "")
("type script" "")
("typesetted boxes" "")
("typewriter" "")
("typewriter small caps" "")
("typing a simple text" "")
("typing simple texts" "")
("ugaritic" "")
("ukrainian" "乌克兰语")
("underbrace" "")
("underline" "下划线")
("undo" "撤销")
("undo last changes" "")
("unfold" "展开")
("up" "")
("update" "更新")
("update from web" "")
("update image links" "")
("upper border" "上端")
("upright" "正体")
("use TeXmacs" "")
("use a black color" "")
("use a blue color" "")
("use a bold font" "")
("use a brown color" "")
("use a calligraphic font" "")
("use a green color" "")
("use a grey color" "")
("use a magenta color" "")
("use a orange color" "")
("use a pink color" "")
("use a red color" "")
("use a sans serif font" "")
("use a typewriter font" "")
("use a white color" "")
("use a yellow color" "")
("use blackboard bold font" "")
("use bold font series" "")
("use calligraphical font" "")
("use footnote font size" "")
("use fraktur font" "")
("use huge font size" "")
("use italic font shape" "")
("use large font size" "")
("use left hand column as border" "")
("use medium font series" "")
("use normal font size" "")
("use package" "")
("use paragraph width" "")
("use really huge font size" "")
("use right font shape" "")
("use right hand column as border" "")
("use roman font family" "")
("use row above as border" "")
("use row below as border" "")
("use sans serif font family" "")
("use script font size" "")
("use slanted font shape" "")
("use small capitals" "")
("use small font size" "")
("use small-caps font shape" "")
("use the blackboard bold font" "")
("use the fraktur font" "")
("use tiny font font size" "")
("use typewriter font family" "")
("use very large font size" "")
("user manual" "用户手册")
("user provided icons" "用户工具栏")
("users of Cyrillic languages" "")
("value" "")
("variable" "")
("variant" "字族")
("vector" "")
("verbatim" "")
("verse" "韵文")
("version" "版本")
("versioning tool" "版本工具")
("vertical" "")
("vertical after" "")
("vertical before" "")
("vertical cell alignment" "")
("vertical part" "竖直部分")
("vertical position" "")
("vertical space" "")
("vertical alignment" "竖直对齐")
("vertically align cell to the base" "")
("vertically center the cell" "")
("very large" "很大")
("very small" "很小")
("vietnamese" "")
("view" "查看")
("visible" "")
("warning" "警告")
("web" "网络")
("welcome" "欢迎")
("welcome to GNU TeXmacs" "欢迎使用 GNU TeXmacs")
("what is new" "")
("when finished" "")
("while" "")
("white" "白色")
("wide accent" "")
("wide bar" "")
("width" "宽度")
("width is exactly the specified width" "")
("width is maximum of specified width and box width" "")
("width is minimum of specified width and box width" "")
("width magnification" "")
("window" "")
("window height" "")
("window width" "")
("windows key" "")
("with" "")
("write a macro" "")
("write a name" "")
("write bold mathematics" "")
("write bold text" "")
("write italic text" "")
("write sample text" "")
("write strong text" "")
("write typewriter text" "")
("write verbatim text" "")
("writing data converters" "")
("writing your own style files" "")
("written with TeXmacs" "使用 TeXmacs 制作")
("yellow" "黄色")
("you can also obtain" "")
("your document is back in its original state" "")
("your first interface" "")
("your language" "使用语言")
